### PR TITLE
Serializers should serialize to string and deserialize from strings.

### PR DESCRIPTION
**Pull request by remi-san**
Some BC changes here. Not anything too radical, but BC nonetheless.

The serializing / deserializing logic was split between different classes. Now, serializers must do all the (de)serializing stuff (to and from strings).

There was no good reason the event should implement or extend something else for being serialized or published (at least, not in the interface signature).

Hence, as new burrow version also contained league stuff, had to create a new major after deleting it and incremented the minimum version to 3.0

### CODE REVIEW

**Comment by SelrahcD** [comment]
I'm not opposed to the modification but I would go with two interfaces, one for serialization and one for deserialization, even if in the end a class implements the two of them.
And to be nice to current users (me, mostly...) I would like to have an implementation of the (de)serializer dealing with JSON encoding like in previous version, helping transition from v2.0 to v3.0 and staying in the spirit of this repo : not having to create the same implementation over and over in our projects :)

**Comment by remi-san** [comment]
I don't see the advantages of separating the interfaces for serializing/deserializing... Maybe I'm missing something but I feel that if you serialize something, you must be able to deserialize it, hence I wouldn't separate them. But I'm not opposed to the idea.

As for the transition, I can't agree. If you don't want the new behavior (where everything is done in the (de)serializer), that's not a problem: we'll have to change the major version because of the BC nature of this PR. So unless you required the lib in your composer.json allowing updates to jump to other majors, you're safe. Or maybe you were thinking of something else?

**Comment by SelrahcD** [comment]
> I don't see the advantages of separating the interfaces for serializing/deserializing... Maybe I'm missing something but I feel that if you serialize an object, you must be able to deserialize it, hence I wouldn't separate them. But I'm not opposed to the idea.

Interface segregation for the win. Small win here I agree. Here we have two contracts and we could use two different objects, one for each role. We probably won't but if we want to we will be able to do it.

Transition : 
I think we should all upgrade as soon as we can because we are all maintaining the thing. If we can avoid to deal with the same issues on several versions I think we should go this way, so I'll be willing to upgrade. I have no issue with adding a serializer and a deserializer but I would like to have an implementation provided in this repo (doing the same de/serilization as before) because this is something we will implement over and over in each project and the starting point of this repo was to minimize boilerplate code in each project.

**Comment by remi-san** [comment]
Ok, it's been done.

Interfaces have been split.

A json serializer has been provided again for the events

**Comment by SelrahcD** [comment]
Nice !
Ready to merge ?

**Comment by remi-san** [comment]
Yep, up to you.

**Pull request merged**
